- hosts: all
  tasks:
  - name: test connection
    ping:

  - name: ensure that os has the latest apt updates
    apt:
      update_cache: yes
    become: true

  - name: install apache
    apt:
      name: apache2
      state: latest
    become: true
